local ____lualib = require("lualib_bundle")
local __TS__ArrayIncludes = ____lualib.__TS__ArrayIncludes
local __TS__SourceMapTraceBack = ____lualib.__TS__SourceMapTraceBack
__TS__SourceMapTraceBack(debug.getinfo(1).short_src, {["5"] = 3,["6"] = 5,["7"] = 7,["8"] = 8,["9"] = 9,["10"] = 10,["11"] = 11,["12"] = 12,["13"] = 14,["14"] = 15,["15"] = 17,["16"] = 18,["17"] = 19,["18"] = 20,["19"] = 21,["20"] = 22,["21"] = 23,["22"] = 24,["23"] = 25,["24"] = 26,["25"] = 27,["26"] = 28,["27"] = 29,["28"] = 30,["29"] = 31,["30"] = 32,["31"] = 33,["32"] = 34,["33"] = 35,["34"] = 37,["35"] = 38,["36"] = 39,["37"] = 40,["38"] = 41,["39"] = 42,["40"] = 43,["41"] = 44,["42"] = 45,["43"] = 46,["44"] = 47,["45"] = 48,["46"] = 49,["47"] = 50,["48"] = 51,["49"] = 52,["50"] = 53,["51"] = 54,["52"] = 5});
__DEV = __TS__ArrayIncludes(arg, "--dev")
love.conf = function(t)
    t.appendidentity = false
    t.version = "11.5"
    t.console = false
    t.accelerometerjoystick = true
    t.externalstorage = false
    t.gammacorrect = false
    t.audio.mic = false
    t.audio.mixwithsystem = true
    t.window.title = "Nervous Breakout"
    t.window.icon = nil
    t.window.width = 600
    t.window.height = 600
    t.window.borderless = false
    t.window.resizable = false
    t.window.minwidth = 1
    t.window.minheight = 1
    t.window.fullscreen = false
    t.window.fullscreentype = "desktop"
    t.window.vsync = 1
    t.window.msaa = 0
    t.window.depth = nil
    t.window.stencil = nil
    t.window.display = 1
    t.window.highdpi = false
    t.window.usedpiscale = true
    t.window.x = nil
    t.window.y = nil
    t.modules.audio = true
    t.modules.data = true
    t.modules.event = true
    t.modules.font = true
    t.modules.graphics = true
    t.modules.image = true
    t.modules.joystick = true
    t.modules.keyboard = true
    t.modules.math = true
    t.modules.mouse = true
    t.modules.physics = true
    t.modules.sound = true
    t.modules.system = true
    t.modules.thread = true
    t.modules.timer = true
    t.modules.touch = true
    t.modules.video = true
    t.modules.window = true
end
